### ISSUE TITLE
Unable to connect to cryptDB proxy

### ISSUE THREAD

**Issue by agribu** [yiwenshao/Practical-Cryptdb#2]
I was trying to get everything running. But currently I'm encountering several errors.

1) Execution of ./cdbserver.sh

-> trying to connect via: mysql -u root -pletmein -h 127.0.0.1 -P 3399
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

-> trying to execute ./cdbclient.sh
ERROR 1105 (HY000): #07000MySQL Proxy Lua script failed to execute. Check the error log.
--> on server side, the following message is displayed:
./cdbserver.sh
mkdir: cannot create directory `shadow': File exists
2017-10-30 11:20:02: (critical) plugin proxy 0.8.5 started
2017-10-30 11:20:51: (critical) (lua-error) [/opt/cryptdb/wrapper.lua]
[string "/opt/cryptdb/wrapper.lua"]:6: /opt/cryptdb/obj/libexecute.so: cannot open shared object file: No such file or directory

**Comment by yiwenshao** [comment]
This project is only tested on ubuntu 16.04. I have tried this on a newly installed ubuntu 16.04 and I do not encounter this problem. So I suggest installing ubuntu 16.04 to run this project. If you have problem running this project on a newly installed ubuntu 16.04, then send me more detailed information so that I can repeat this problem.

Also, for this error info, I assume that the problem lies in MySQL-Proxy. SO, you should first start MySQL-Proxy correctly. You can download MySQL-Proxy without using the cryptdb library and try to find if you can run MySQL-Proxy with MySQL-Server correctly.

Also, this project is still under development, and I have updated the README. Hope this will be helpful :)

**Comment by agribu** [comment]
Run from cryptDB directory:
`# mysql-proxy --defaults-file=mysql-proxy.cnf --proxy-lua-script=wrapper.lua`

-- Connect via: --
```
# mysql -u root -pletmein -h 127.0.0.1 -P 3399
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```


TRYING TO TRACE ERROR:

**Step 1**

-- Connect via: --
```
# mysql -u root -pletmein -h 127.0.0.1 -P 3399
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```

-- FIX: --
change 127.0.0.1 to 0.0.0.0 for proxy-address in mysql-proxy.cnf

**Step 2** 

```
$ mysql -u root -pletmein -h 0.0.0.0 -P 3399
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1105 (HY000): #07000MySQL Proxy Lua script failed to load. Check the error log.
```

```
# mysql-proxy --defaults-file=mysql-proxy.cnf --proxy-lua-script=wrapper.lua
2017-11-04 11:20:08: (critical) plugin proxy 0.8.5 started
2017-11-04 11:20:10: (critical) network-mysqld-lua.c:234: lua_load_file(/opt/cryptdb/mysql-src/mysql-proxy-0.8.5/wrapper.lua) failed: lua-scope.c:241: stat(/opt/cryptdb/mysql-src/mysql-proxy-0.8.5/wrapper.lua) failed: No such file or directory (2)
```

-- FIX: --
`cp $CRYPTDB/wrapper.lua /opt/cryptdb/mysql-src/mysql-proxy-0.8.5/`


**Step 3**

```
$ mysql -u root -pletmein -h 0.0.0.0 -P 3399
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1105 (HY000): #07000MySQL Proxy Lua script failed to execute. Check the error log.
```

```
# mysql-proxy --defaults-file=mysql-proxy.cnf --proxy-lua-script=wrapper.lua
2017-11-04 11:21:49: (critical) plugin proxy 0.8.5 started
2017-11-04 11:21:54: (critical) (lua-error) [/opt/cryptdb/mysql-src/mysql-proxy-0.8.5/wrapper.lua]
[string "/opt/cryptdb/mysql-src/mysql-proxy-0.8.5/wr..."]:6: /opt/cryptdb/obj/libexecute.so: cannot open shared object file: No such file or directory
```


SEEMS LIKE SOMETHING WENT WRONG IN BUILDING CRYPTDB!
